version: '3.1'
services:

  insurance:
    image: rinatalibaev/insurance:1.7
    ports:
      - 9099:9099

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: insurance
      PGDATA: /var/lib/postgresql/data/insurance/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8888

volumes:
  db-data:
    driver: local