version: '3.1'
services:

  insurance:
    image: rinatalibaev/insurance:1.6
    ports:
      - 9099:9099

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: insurance

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:9090